# Generated by Django 5.2.8 on 2025-11-17 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(choices=[('gemini-pro', 'Gemini Pro'), ('gemini-pro-vision', 'Gemini Pro Vision')], default='gemini-pro', max_length=50)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'db_table': 'ai_configs',
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('text', 'Text'), ('screen_recording', 'Screen Recording')], max_length=20)),
                ('input_data', models.TextField(help_text='Input data or description')),
                ('expected_output', models.JSONField(help_text='Expected AI response in JSON format')),
                ('actual_output', models.JSONField(blank=True, help_text='Actual AI response', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether AI response was correct', null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('used_for_training', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Training Data',
                'db_table': 'ai_training_data',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('validation_type', models.CharField(choices=[('photo', 'Photo Analysis'), ('audio', 'Audio Analysis'), ('text', 'Text Analysis'), ('screen_recording', 'Screen Recording Analysis'), ('general', 'General Validation')], max_length=20)),
                ('prompt_template', models.TextField(help_text='Template for AI validation prompt. Use {validation_prompt} for habit-specific prompt.')),
                ('confidence_threshold', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_processing_time', models.IntegerField(default=15, help_text='Seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'validation_rules',
                'ordering': ['validation_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('false_positive', 'False Positive - Wrongly Approved'), ('false_negative', 'False Negative - Wrongly Rejected'), ('accuracy', 'Accuracy Feedback'), ('suggestion', 'Suggestion'), ('bug', 'Bug Report')], max_length=20)),
                ('description', models.TextField()),
                ('expected_result', models.TextField(help_text='What the user expected')),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.dailycheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data_preview', models.TextField(blank=True, help_text='Preview of the input data sent to AI')),
                ('ai_response_raw', models.TextField(blank=True, help_text='Raw response from AI')),
                ('ai_response_parsed', models.JSONField(default=dict, help_text='Parsed JSON response from AI')),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_approved', models.BooleanField(default=False)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='core.dailycheckin')),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_validation.validationrule')),
            ],
            options={
                'db_table': 'validation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(help_text='SHA256 hash of input data', max_length=64, unique=True)),
                ('input_data_preview', models.TextField()),
                ('ai_response', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('is_approved', models.BooleanField()),
                ('usage_count', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_validation.validationrule')),
            ],
            options={
                'db_table': 'validation_cache',
                'indexes': [models.Index(fields=['input_hash'], name='validation__input_h_dcf81f_idx'), models.Index(fields=['last_used'], name='validation__last_us_b8a74e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('user_accuracy_score', models.FloatField(default=0.0, help_text='Based on user feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_validation.validationrule')),
            ],
            options={
                'verbose_name_plural': 'Model Performance Metrics',
                'db_table': 'model_performance',
                'unique_together': {('validation_rule', 'date')},
            },
        ),
    ]
