# Generated by Django 5.2.8 on 2025-12-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationlog',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='validationlog',
            name='validation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_validation.validationrule'),
        ),
    ]
