# Generated by Django 5.2.8 on 2025-11-17 06:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('learning', 'Learning'), ('productivity', 'Productivity'), ('health', 'Health'), ('creative', 'Creative'), ('mindfulness', 'Mindfulness'), ('other', 'Other')], max_length=20)),
                ('project_type', models.CharField(choices=[('30_day_challenge', '30-Day Challenge'), ('project_completion', 'Project Completion'), ('skill_development', 'Skill Development'), ('habit_formation', 'Habit Formation')], default='30_day_challenge', max_length=20)),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('project_description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('validation_method', models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('text', 'Text'), ('screen_recording', 'Screen Recording'), ('self_report', 'Self Report')], max_length=20)),
                ('target_duration', models.IntegerField(default=1, help_text='Minutes')),
                ('target_count', models.IntegerField(default=1, help_text='For countable habits')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Moderate'), (4, 'Challenging'), (5, 'Very Challenging')], default=3)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('validation_prompt', models.TextField(help_text='What the AI should look for')),
                ('min_confidence', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.goal')),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('streak', 'Streak'), ('completion', 'Completion'), ('consistency', 'Consistency'), ('progress', 'Progress')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('celebration_message', models.TextField(blank=True)),
                ('is_celebrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.goal')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('success_pattern', 'Success Pattern'), ('struggle_detection', 'Struggle Detection'), ('time_optimization', 'Time Optimization'), ('difficulty_adjustment', 'Difficulty Adjustment'), ('milestone_celebration', 'Milestone Celebration'), ('general_insight', 'General Insight')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_actionable', models.BooleanField(default=False)),
                ('action_title', models.CharField(blank=True, max_length=200)),
                ('action_description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.goal')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_goals', models.IntegerField(default=0)),
                ('completed_goals', models.IntegerField(default=0)),
                ('total_habits', models.IntegerField(default=0)),
                ('active_habits', models.IntegerField(default=0)),
                ('overall_success_rate', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_checkins', models.IntegerField(default=0)),
                ('total_time_invested', models.IntegerField(default=0, help_text='Total minutes invested')),
                ('average_daily_time', models.FloatField(default=0.0)),
                ('milestones_achieved', models.IntegerField(default=0)),
                ('insights_generated', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='checkin_photos/')),
                ('audio_proof', models.FileField(blank=True, null=True, upload_to='checkin_audio/')),
                ('text_proof', models.TextField(blank=True)),
                ('screen_recording_proof', models.FileField(blank=True, null=True, upload_to='screen_recordings/')),
                ('ai_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('is_self_report', models.BooleanField(default=False)),
                ('self_report_description', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(blank=True, help_text='Time spent in minutes', null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.habit')),
            ],
            options={
                'db_table': 'daily_checkins',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_checkin', models.DateField(blank=True, null=True)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='core.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streaks',
                'unique_together': {('user', 'habit')},
            },
        ),
    ]
